<?php

namespace AppBundle\Repository;

/**
 * AclEntry
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AclEntry extends \Doctrine\ORM\EntityRepository
{
}
