<?php

namespace AppBundle\Repository;

/**
 * AclResource
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AclResource extends \Doctrine\ORM\EntityRepository
{
}
