<?php

namespace AppBundle\Repository;

/**
 * AclRole
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AclRole extends \Doctrine\ORM\EntityRepository
{
}
