AppBundle\Entity\AclRole:
    type: entity
    repositoryClass: AppBundle\Repository\AclRole
    table: acl_role
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
        slug:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
        description:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
    lifecycleCallbacks: {  }
